jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:3306/eshopDB03?characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
jdbc.username=root
jdbc.password=1111
initialSize=10
maxActive=10
maxIdle=10
minIdle=0
maxWait=5
#172.16.6.53